# Generated by Django 3.1.7 on 2021-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
